<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Str;
use App\Models\Country;

class CountriesTablesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('countries')->insert(
        [
            ['status' => false, 'name' => 'Afghanistan', 'code' => 'AF', 'indicative' => '+97'],
            ['status' => false, 'name' => 'Aland', 'code' => 'AX', 'indicative' => '+358'],
            ['status' => false, 'name' => 'Albanie', 'code' => 'AL', 'indicative' => '+355'],
            ['status' => false, 'name' => 'Algerie', 'code' => 'DZ', 'indicative' => '+213'],
            ['status' => false, 'name' => 'Samoa Américaines', 'code' => 'AS', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Andorre', 'code' => 'AD', 'indicative' => '+376'],
            ['status' => false, 'name' => 'Angola', 'code' => 'AO', 'indicative' => '+244'],
            ['status' => false, 'name' => 'Anguille', 'code' => 'AI', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Antarctique', 'code' => 'AQ', 'indicative' => '+672'],
            ['status' => false, 'name' => 'Antigua-et-Barbuda', 'code' => 'AG', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Argentine', 'code' => 'AR', 'indicative' => '+54'],
            ['status' => false, 'name' => 'Armenie', 'code' => 'AM', 'indicative' => '+374'],
            ['status' => false, 'name' => 'Aruba', 'code' => 'AW', 'indicative' => '+297'],
            ['status' => false, 'name' => 'Australie', 'code' => 'AU', 'indicative' => '+61'],
            ['status' => false, 'name' => 'Autriche', 'code' => 'AT', 'indicative' => '+43'],
            ['status' => false, 'name' => 'Azerbaijan', 'code' => 'AZ', 'indicative' => '+994'],
            ['status' => false, 'name' => 'Bahamas', 'code' => 'BS', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Bahreïn', 'code' => 'BH', 'indicative' => '+973'],
            ['status' => false, 'name' => 'Bangladesh', 'code' => 'BD', 'indicative' => '+880'],
            ['status' => false, 'name' => 'Barbade', 'code' => 'BB', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Biélorussie', 'code' => 'BY', 'indicative' => '+375'],
            ['status' => false, 'name' => 'Belgique', 'code' => 'BE', 'indicative' => '+32'],
            ['status' => false, 'name' => 'Belize', 'code' => 'BZ', 'indicative' => '+501'],
            ['status' => true, 'name' => 'Bénin', 'code' => 'BJ', 'indicative' => '+229'],
            ['status' => false, 'name' => 'Bermudes', 'code' => 'BM', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Bhoutan', 'code' => 'BT', 'indicative' => '+975'],
            ['status' => false, 'name' => 'Bolivie', 'code' => 'BO', 'indicative' => '+591'],
            ['status' => false, 'name' => 'Bonaire, Saint-Eustache et Saba', 'code' => 'BQ', 'indicative' => '+'],
            ['status' => false, 'name' => 'Bosnie-Herzégovine', 'code' => 'BA', 'indicative' => '+387'],
            ['status' => false, 'name' => 'Botswana', 'code' => 'BW', 'indicative' => '+267'],
            ['status' => false, 'name' => 'Île Bouvet', 'code' => 'BV', 'indicative' => '+47'],
            ['status' => false, 'name' => 'Brésil', 'code' => 'BR', 'indicative' => '+55'],
            ['status' => false, 'name' => 'Territoire Britannique de l\'Océan Indien', 'code' => 'IO', 'indicative' => '+246'],
            ['status' => false, 'name' => 'Brunei', 'code' => 'BN', 'indicative' => '+673'],
            ['status' => false, 'name' => 'Bulgarie', 'code' => 'BG', 'indicative' => '+359'],
            ['status' => true, 'name' => 'Burkina Faso', 'code' => 'BF', 'indicative' => '+226'],
            ['status' => false, 'name' => 'Burundi', 'code' => 'BI', 'indicative' => '+257'],
            ['status' => false, 'name' => 'Cambodge', 'code' => 'KH', 'indicative' => '+855'],
            ['status' => true, 'name' => 'Cameroun', 'code' => 'CM', 'indicative' => '+237'],
            ['status' => false, 'name' => 'Canada', 'code' => 'CA', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Cap-Vert', 'code' => 'CV', 'indicative' => '+238'],
            ['status' => false, 'name' => 'Îles Caïmans', 'code' => 'KY', 'indicative' => '+1'],
            ['status' => false, 'name' => 'République centrafricaine', 'code' => 'CF', 'indicative' => '+236'],
            ['status' => false, 'name' => 'Tchad', 'code' => 'TD', 'indicative' => '+235'],
            ['status' => false, 'name' => 'Chili', 'code' => 'CL', 'indicative' => '+56'],
            ['status' => false, 'name' => 'Chine', 'code' => 'CH', 'indicative' => '+86'],
            ['status' => false, 'name' => 'Christmas Island', 'code' => 'CX', 'indicative' => '+61'],
            ['status' => false, 'name' => 'Îles Cocos', 'code' => 'CC', 'indicative' => '+61'],
            ['status' => false, 'name' => 'Colombie', 'code' => 'CO', 'indicative' => '+57'],
            ['status' => false, 'name' => 'Comoros', 'code' => 'KM', 'indicative' => '+269'],
            ['status' => false, 'name' => 'Congo', 'code' => 'CG', 'indicative' => '+242'],
            ['status' => false, 'name' => 'République Démocratique Congo', 'code' => 'CD', 'indicative' => '+243'],
            ['status' => false, 'name' => 'Îles Cook', 'code' => 'CK', 'indicative' => '+682'],
            ['status' => false, 'name' => 'Costa Rica', 'code' => 'CR', 'indicative' => '+506'],
            ['status' => true, 'name' => 'Côte d\'Ivoire', 'code' => 'CI', 'indicative' => '+225'],
            ['status' => false, 'name' => 'Croatie', 'code' => 'HR', 'indicative' => '+385'],
            ['status' => false, 'name' => 'Cuba', 'code' => 'CU', 'indicative' => '+53'],
            ['status' => false, 'name' => 'Curaçao', 'code' => 'CW', 'indicative' => '+599'],
            ['status' => false, 'name' => 'Chypre', 'code' => 'CY', 'indicative' => '+357'],
            ['status' => false, 'name' => 'République tchèque', 'code' => 'CZ', 'indicative' => '+420'],
            ['status' => false, 'name' => 'Danemark', 'code' => 'DK', 'indicative' => '+45'],
            ['status' => false, 'name' => 'Djibouti', 'code' => 'DJ', 'indicative' => '+253'],
            ['status' => false, 'name' => 'Dominique', 'code' => 'DM', 'indicative' => '+1'],
            ['status' => false, 'name' => 'République Dominicaine', 'code' => 'DO', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Equateur', 'code' => 'EC', 'indicative' => '+593'],
            ['status' => false, 'name' => 'Egypte', 'code' => 'EG', 'indicative' => '+20'],
            ['status' => false, 'name' => 'El Salvador', 'code' => 'SV', 'indicative' => '+503'],
            ['status' => false, 'name' => 'Guinée équatoriale', 'code' => 'GQ', 'indicative' => '+240'],
            ['status' => false, 'name' => 'Érythrée', 'code' => 'ER', 'indicative' => '+291'],
            ['status' => false, 'name' => 'Estonie', 'code' => 'EE', 'indicative' => '+372'],
            ['status' => false, 'name' => 'Ethiopie', 'code' => 'ET', 'indicative' => '+251'],
            ['status' => false, 'name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'indicative' => '+500'],
            ['status' => false, 'name' => 'Îles Féroé', 'code' => 'FO', 'indicative' => '+298'],
            ['status' => false, 'name' => 'Fidji', 'code' => 'FJ', 'indicative' => '+679'],
            ['status' => false, 'name' => 'Finlande', 'code' => 'FI', 'indicative' => '+358'],
            ['status' => false, 'name' => 'France', 'code' => 'FR', 'indicative' => '+33'],
            ['status' => false, 'name' => 'Guyane', 'code' => 'GF', 'indicative' => '+594'],
            ['status' => false, 'name' => 'Polynésie française', 'code' => 'PF', 'indicative' => '+689'],
            ['status' => false, 'name' => 'Terres Australes Françaises', 'code' => 'TF', 'indicative' => '+'],
            ['status' => false, 'name' => 'Gabon', 'code' => 'GA', 'indicative' => '+241'],
            ['status' => false, 'name' => 'Gambie', 'code' => 'GM', 'indicative' => '+220'],
            ['status' => false, 'name' => 'Géorgie', 'code' => 'GE', 'indicative' => '+995'],
            ['status' => false, 'name' => 'Allemagne', 'code' => 'DE', 'indicative' => '+49'],
            ['status' => false, 'name' => 'Ghana', 'code' => 'GH', 'indicative' => '+233'],
            ['status' => false, 'name' => 'Gibraltar', 'code' => 'GI', 'indicative' => '+350'],
            ['status' => false, 'name' => 'Grèce', 'code' => 'GR', 'indicative' => '+30'],
            ['status' => false, 'name' => 'Groenland', 'code' => 'GL', 'indicative' => '+299'],
            ['status' => false, 'name' => 'Grenade', 'code' => 'GD', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Guadeloupe', 'code' => 'GP', 'indicative' => '+590'],
            ['status' => false, 'name' => 'Guam', 'code' => 'GU', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Guatemala', 'code' => 'GT', 'indicative' => '+502'],
            ['status' => false, 'name' => 'Guernesey', 'code' => 'GG', 'indicative' => '+44'],
            ['status' => false, 'name' => 'Guinée', 'code' => 'GN', 'indicative' => '+224'],
            ['status' => true, 'name' => 'Guinée-Bissau', 'code' => 'GW', 'indicative' => '+245'],
            ['status' => false, 'name' => 'Guyana', 'code' => 'GY', 'indicative' => '+592'],
            ['status' => false, 'name' => 'Haiti', 'code' => 'HT', 'indicative' => '+509'],
            ['status' => false, 'name' => 'Île Heard et Îles McDonald Mcdonald', 'code' => 'HM', 'indicative' => '+'],
            ['status' => false, 'name' => 'Vatican', 'code' => 'VA', 'indicative' => '+379'],
            ['status' => false, 'name' => 'Honduras', 'code' => 'HN', 'indicative' => '+504'],
            ['status' => false, 'name' => 'Hong Kong', 'code' => 'HK', 'indicative' => '+852'],
            ['status' => false, 'name' => 'Hongrie', 'code' => 'HU', 'indicative' => '+36'],
            ['status' => false, 'name' => 'Island', 'code' => 'IS', 'indicative' => '+354'],
            ['status' => false, 'name' => 'Inde', 'code' => 'IN', 'indicative' => '+91'],
            ['status' => false, 'name' => 'Indonésie', 'code' => 'ID', 'indicative' => '+62'],
            ['status' => false, 'name' => 'Iran', 'code' => 'IR', 'indicative' => '+98'],
            ['status' => false, 'name' => 'Iraq', 'code' => 'IQ', 'indicative' => '+964'],
            ['status' => false, 'name' => 'Irland', 'code' => 'IE', 'indicative' => '+353'],
            ['status' => false, 'name' => 'Isle of Man', 'code' => 'IM', 'indicative' => '+44'],
            ['status' => false, 'name' => 'Israël', 'code' => 'IL', 'indicative' => '+972'],
            ['status' => false, 'name' => 'Italie', 'code' => 'IT', 'indicative' => '+39'],
            ['status' => false, 'name' => 'Jamaïque', 'code' => 'JM', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Japon', 'code' => 'JP', 'indicative' => '+81'],
            ['status' => false, 'name' => 'Jersey', 'code' => 'JE', 'indicative' => '+44'],
            ['status' => false, 'name' => 'Jordan', 'code' => 'JO', 'indicative' => '+962'],
            ['status' => false, 'name' => 'Kazakhstan', 'code' => 'KZ', 'indicative' => '+7'],
            ['status' => false, 'name' => 'Kenya', 'code' => 'KE', 'indicative' => '+254'],
            ['status' => false, 'name' => 'Kiribati', 'code' => 'KI', 'indicative' => '+686'],
            ['status' => false, 'name' => 'Corée du Sud', 'code' => 'CS', 'indicative' => '+82'],
            ['status' => false, 'name' => 'Corée du Nord', 'code' => 'CN', 'indicative' => '+850'],
            ['status' => false, 'name' => 'Koweït', 'code' => 'KW', 'indicative' => '+965'],
            ['status' => false, 'name' => 'Kyrgyzstan', 'code' => 'KG', 'indicative' => '+996'],
            ['status' => false, 'name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'indicative' => '+856'],
            ['status' => false, 'name' => 'Latvia', 'code' => 'LV', 'indicative' => '+371'],
            ['status' => false, 'name' => 'Lebanon', 'code' => 'LB', 'indicative' => '+961'],
            ['status' => false, 'name' => 'Lesotho', 'code' => 'LS', 'indicative' => '+266'],
            ['status' => false, 'name' => 'Liberia', 'code' => 'LR', 'indicative' => '+231'],
            ['status' => false, 'name' => 'Libye', 'code' => 'LY', 'indicative' => '+218'],
            ['status' => false, 'name' => 'Liechtenstein', 'code' => 'LI', 'indicative' => '+423'],
            ['status' => false, 'name' => 'Lithuanie', 'code' => 'LT', 'indicative' => '+370'],
            ['status' => false, 'name' => 'Luxembourg', 'code' => 'LU', 'indicative' => '+352'],
            ['status' => false, 'name' => 'Macao', 'code' => 'MO', 'indicative' => '+853'],
            ['status' => false, 'name' => 'Macedoine', 'code' => 'MK', 'indicative' => '+389'],
            ['status' => false, 'name' => 'Madagascar', 'code' => 'MG', 'indicative' => '+261'],
            ['status' => false, 'name' => 'Malawi', 'code' => 'MW', 'indicative' => '+265'],
            ['status' => false, 'name' => 'Malaysie', 'code' => 'MY', 'indicative' => '+60'],
            ['status' => false, 'name' => 'Maldives', 'code' => 'MV', 'indicative' => '+960'],
            ['status' => true, 'name' => 'Mali', 'code' => 'ML', 'indicative' => '+223'],
            ['status' => false, 'name' => 'Malte', 'code' => 'MT', 'indicative' => '+356'],
            ['status' => false, 'name' => 'Marshall Islands', 'code' => 'MH', 'indicative' => '+692'],
            ['status' => false, 'name' => 'Martinique', 'code' => 'MQ', 'indicative' => '+596'],
            ['status' => false, 'name' => 'Mauritanie', 'code' => 'MR', 'indicative' => '+222'],
            ['status' => false, 'name' => 'Mauritius', 'code' => 'MU', 'indicative' => '+230'],
            ['status' => false, 'name' => 'Mayotte', 'code' => 'YT', 'indicative' => '+262'],
            ['status' => false, 'name' => 'Mexique', 'code' => 'MX', 'indicative' => '+52'],
            ['status' => false, 'name' => 'Micronésie', 'code' => 'FM', 'indicative' => '+691'],
            ['status' => false, 'name' => 'Moldavie', 'code' => 'MD', 'indicative' => '+373'],
            ['status' => false, 'name' => 'Monaco', 'code' => 'MC', 'indicative' => '+377'],
            ['status' => false, 'name' => 'Mongolie', 'code' => 'MN', 'indicative' => '+976'],
            ['status' => false, 'name' => 'Montenegro', 'code' => 'ME', 'indicative' => '+382'],
            ['status' => false, 'name' => 'Montserrat', 'code' => 'MS', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Maroc', 'code' => 'MA', 'indicative' => '+212'],
            ['status' => false, 'name' => 'Mozambique', 'code' => 'MZ', 'indicative' => '+258'],
            ['status' => false, 'name' => 'Myanmar', 'code' => 'MM', 'indicative' => '+95'],
            ['status' => false, 'name' => 'Namibie', 'code' => 'NA', 'indicative' => '+264'],
            ['status' => false, 'name' => 'Nauru', 'code' => 'NR', 'indicative' => '+674'],
            ['status' => false, 'name' => 'Nepal', 'code' => 'NP', 'indicative' => '+977'],
            ['status' => false, 'name' => 'Pays-bas', 'code' => 'NL', 'indicative' => '+31'],
            ['status' => false, 'name' => 'Nouvelle Calédonie', 'code' => 'NC', 'indicative' => '+687'],
            ['status' => false, 'name' => 'Nouvelle Zélande', 'code' => 'NZ', 'indicative' => '+64'],
            ['status' => false, 'name' => 'Nicaragua', 'code' => 'NI', 'indicative' => '+505'],
            ['status' => true, 'name' => 'Niger', 'code' => 'NE', 'indicative' => '+227'],
            ['status' => false, 'name' => 'Nigéria', 'code' => 'NG', 'indicative' => '+234'],
            ['status' => false, 'name' => 'Niue', 'code' => 'NU', 'indicative' => '+683'],
            ['status' => false, 'name' => 'Île Norfolk', 'code' => 'NF', 'indicative' => '+672'],
            ['status' => false, 'name' => 'Îles Mariannes du Nord', 'code' => 'MP', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Norvège', 'code' => 'NO', 'indicative' => '+47'],
            ['status' => false, 'name' => 'Oman', 'code' => 'OM', 'indicative' => '+968'],
            ['status' => false, 'name' => 'Pakistan', 'code' => 'PK', 'indicative' => '+92'],
            ['status' => false, 'name' => 'Palau', 'code' => 'PW', 'indicative' => '+680'],
            ['status' => false, 'name' => 'Palestine, State of', 'code' => 'PS', 'indicative' => '+970'],
            ['status' => false, 'name' => 'Panama', 'code' => 'PA', 'indicative' => '+507'],
            ['status' => false, 'name' => 'Papouasie Nouvelle Guinée', 'code' => 'PG', 'indicative' => '+675'],
            ['status' => false, 'name' => 'Paraguay', 'code' => 'PY', 'indicative' => '+595'],
            ['status' => false, 'name' => 'Pérou', 'code' => 'PE', 'indicative' => '+51'],
            ['status' => false, 'name' => 'Philippines', 'code' => 'PH', 'indicative' => '+63'],
            ['status' => false, 'name' => 'Pitcairn', 'code' => 'PN', 'indicative' => '+64'],
            ['status' => false, 'name' => 'Pologne', 'code' => 'PL', 'indicative' => '+48'],
            ['status' => false, 'name' => 'Portugal', 'code' => 'PT', 'indicative' => '+351'],
            ['status' => false, 'name' => 'Puerto Rico', 'code' => 'PR', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Qatar', 'code' => 'QA', 'indicative' => '+974'],
            ['status' => false, 'name' => 'Réunion', 'code' => 'RE', 'indicative' => '+262'],
            ['status' => false, 'name' => 'Roumanie', 'code' => 'RO', 'indicative' => '+40'],
            ['status' => false, 'name' => 'Russie', 'code' => 'RU', 'indicative' => '+7'],
            ['status' => false, 'name' => 'Rwanda', 'code' => 'RW', 'indicative' => '+250'],
            ['status' => false, 'name' => 'Saint Barthélemy', 'code' => 'BL', 'indicative' => '+590'],
            ['status' => false, 'name' => 'Sainte Hélène, Ascension et Tristan da Cunha', 'code' => 'SH', 'indicative' => '+290'],
            ['status' => false, 'name' => 'Saint Kitts et Nevis', 'code' => 'KN', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Sainte Lucie', 'code' => 'LC', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Saint Martin', 'code' => 'MF', 'indicative' => '+590'],
            ['status' => false, 'name' => 'Saint Pierre et Miquelon', 'code' => 'PM', 'indicative' => '+508'],
            ['status' => false, 'name' => 'Saint Vincent et les Grenadines', 'code' => 'VC', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Samoa', 'code' => 'WS', 'indicative' => '+685'],
            ['status' => false, 'name' => 'Saint Marin', 'code' => 'SM', 'indicative' => '+378'],
            ['status' => false, 'name' => 'Sao Tomé-et-Principe', 'code' => 'ST', 'indicative' => '+239'],
            ['status' => false, 'name' => 'Arabie saoudite', 'code' => 'SA', 'indicative' => '+966'],
            ['status' => true, 'name' => 'Sénégal', 'code' => 'SN', 'indicative' => '+221'],
            ['status' => false, 'name' => 'Serbie', 'code' => 'RS', 'indicative' => '+381'],
            ['status' => false, 'name' => 'Seychelles', 'code' => 'SC', 'indicative' => '+248'],
            ['status' => false, 'name' => 'Sierra Leone', 'code' => 'SL', 'indicative' => '+232'],
            ['status' => false, 'name' => 'Singapour', 'code' => 'SG', 'indicative' => '+65'],
            ['status' => false, 'name' => 'Sint Maarten (Dutch part)', 'code' => 'SX', 'indicative' => '+721'],
            ['status' => false, 'name' => 'Slovaquie', 'code' => 'SK', 'indicative' => '+421'],
            ['status' => false, 'name' => 'Slovénie', 'code' => 'SI', 'indicative' => '+386'],
            ['status' => false, 'name' => 'îles Salomon', 'code' => 'SB', 'indicative' => '+677'],
            ['status' => false, 'name' => 'Somalie', 'code' => 'SO', 'indicative' => '+252'],
            ['status' => false, 'name' => 'Afrique du Sud', 'code' => 'ZA', 'indicative' => '+27'],
            ['status' => false, 'name' => 'Géorgie du Sud et îles Sandwich du Sud', 'code' => 'GS', 'indicative' => '+500'],
            ['status' => false, 'name' => 'Soudan du Sud', 'code' => 'SS', 'indicative' => '+211'],
            ['status' => false, 'name' => 'Espagne', 'code' => 'ES', 'indicative' => '+34'],
            ['status' => false, 'name' => 'Sri Lanka', 'code' => 'LK', 'indicative' => '+94'],
            ['status' => false, 'name' => 'Soudan', 'code' => 'SD', 'indicative' => '+249'],
            ['status' => false, 'name' => 'Suriname', 'code' => 'SR', 'indicative' => '+597'],
            ['status' => false, 'name' => 'Svalbard et Jan Mayen', 'code' => 'SJ', 'indicative' => '+47'],
            ['status' => false, 'name' => 'Swaziland', 'code' => 'SZ', 'indicative' => '+268'],
            ['status' => false, 'name' => 'Suède', 'code' => 'SE', 'indicative' => '+46'],
            ['status' => false, 'name' => 'Suisse', 'code' => 'SUI', 'indicative' => '+41'],
            ['status' => false, 'name' => 'Syrie', 'code' => 'SY', 'indicative' => '+963'],
            ['status' => false, 'name' => 'Taiwan', 'code' => 'TW', 'indicative' => '+886'],
            ['status' => false, 'name' => 'Tadjikistan', 'code' => 'TJ', 'indicative' => '+992'],
            ['status' => false, 'name' => 'Tanzanie', 'code' => 'TZ', 'indicative' => '+255'],
            ['status' => false, 'name' => 'Thaïlande', 'code' => 'TH', 'indicative' => '+66'],
            ['status' => false, 'name' => 'Timor-Leste', 'code' => 'TL', 'indicative' => '+670'],
            ['status' => true, 'name' => 'Togo', 'code' => 'TG', 'indicative' => '+228'],
            ['status' => false, 'name' => 'Tokelau', 'code' => 'TK', 'indicative' => '+690'],
            ['status' => false, 'name' => 'Tonga', 'code' => 'TO', 'indicative' => '+676'],
            ['status' => false, 'name' => 'Trinité et Tobago', 'code' => 'TT', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Tunisie', 'code' => 'TN', 'indicative' => '+216'],
            ['status' => false, 'name' => 'Turquie', 'code' => 'TR', 'indicative' => '+90'],
            ['status' => false, 'name' => 'Turkménistan', 'code' => 'TM', 'indicative' => '+993'],
            ['status' => false, 'name' => 'îles Turques et Caïques', 'code' => 'TC', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Tuvalu', 'code' => 'TV', 'indicative' => '+688'],
            ['status' => false, 'name' => 'Ouganda', 'code' => 'UG', 'indicative' => '+256'],
            ['status' => false, 'name' => 'Ukraine', 'code' => 'UA', 'indicative' => '+380'],
            ['status' => false, 'name' => 'Émirats arabes unis', 'code' => 'AE', 'indicative' => '+971'],
            ['status' => false, 'name' => 'Royaume-Uni', 'code' => 'GB', 'indicative' => '+44'],
            ['status' => false, 'name' => 'États-Unis', 'code' => 'US', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Îles mineures éloignées des États-Unis', 'code' => 'UM', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Uruguay', 'code' => 'UY', 'indicative' => '+598'],
            ['status' => false, 'name' => 'Ouzbékistan', 'code' => 'UZ', 'indicative' => '+998'],
            ['status' => false, 'name' => 'Vanuatu', 'code' => 'VU', 'indicative' => '+678'],
            ['status' => false, 'name' => 'Vénézuela', 'code' => 'VE', 'indicative' => '+58'],
            ['status' => false, 'name' => 'Viet Nam', 'code' => 'VN', 'indicative' => '+84'],
            ['status' => false, 'name' => 'Les iles vierges, British', 'code' => 'VG', 'indicative' => '+1 284'],
            ['status' => false, 'name' => 'Les iles vierges, U.S.', 'code' => 'VI', 'indicative' => '+1'],
            ['status' => false, 'name' => 'Wallis et Futuna', 'code' => 'WF', 'indicative' => '+681'],
            ['status' => false, 'name' => 'Sahara occidental', 'code' => 'EH', 'indicative' => '+212'],
            ['status' => false, 'name' => 'Yémen', 'code' => 'YE', 'indicative' => '+967'],
            ['status' => false, 'name' => 'Zambie', 'code' => 'ZM', 'indicative' => '+260'],
            ['status' => false, 'name' => 'Zimbabwé', 'code' => 'ZW', 'indicative' => '+263'],
        ]);
    }
}
